name: Debug Check Suite Events
on:
  check_suite:
    types: [requested, rerequested, completed]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug all check suite events
        run: |
          echo "Event: ${{ github.event.action }}"
          echo "Conclusion: ${{ github.event.check_suite.conclusion }}"
          echo "Status: ${{ github.event.check_suite.status }}"
          echo "PR count: ${{ github.event.check_suite.pull_requests && length(github.event.check_suite.pull_requests) || 0 }}"
          echo "App: ${{ github.event.check_suite.app.name }}"