name: Random Number Generator

on:
  push:
    branches: [main]
    
  workflow_dispatch:

jobs:
  generate-random-number:
    runs-on: ubuntu-latest
    steps:
      - name: Generate random number
        id: random
        run: echo "value=$((RANDOM % 100 + 1))" >> $GITHUB_OUTPUT

      - name: Show random number
        run: echo "Random number is ${{ steps.random.outputs.value }}"